import { formatOptions } from "./";

export const SEGMENT_FILTER_TYPE = formatOptions([
  "Added Last Month",
  "Added Last Week",
  "Added This Month",
  "Added This Week",
  "Added This Year",
  "Age",
  "Contact is Archived",
  "Assigned No Is",
  "Birthday",
  "Birthdays This Month",
  "Birthdays This Week",
  "Birthdays Today",
  "Company",
  "Has been Contacted",
  "Contacted Last Month",
  "Contacted Last Week",
  "Contacted This Month",
  "Contacted This Week",
  "Contacted This Year",
  "Created Date",
  "Is Customer",
  "Email",
  "Is Facebook Contact",
  "Form Completed",
  "Has Gender",
  "Contact is Hidden",
  "Industry",
  "Job Title",
  "Last Contacted",
  "Last Updated",
  "Clicked",
  "Lives In",
  "Messages Exchanged",
  "Messages Incoming",
  "Messages Outgoing",
  "Mobile",
  "Has Purchased",
  "Purchased",
  "Responded",
  "Revenue",
  "Include Segment",
  "Sent Update",
  "Is Subscribed",
  "Is Tagged",
  "Is VIP",
]);
